#!/bin/bash
for branch in `git branch -r` ; do \
  if [ $branch != 'origin/HEAD' ] && \
     [ $branch != '->' ] && \
     [ `echo $branch | cut -d "/" -f2 - ` != \
       `git branch | cut -d " " -f2 -` ] ; \
  then \
    git branch --track `echo $branch | cut -d "/" -f2 - ` $branch; \
  fi \
done
git fetch --tags
